"""empty message

Revision ID: 0580125cd965
Revises: c9597accf5b7
Create Date: 2022-03-18 18:43:01.071214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0580125cd965'
down_revision = 'c9597accf5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
