"""empty message

Revision ID: 4edcb861f39e
Revises: 0580125cd965
Create Date: 2022-03-18 18:43:11.639730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edcb861f39e'
down_revision = '0580125cd965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('first_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'first_name')
    # ### end Alembic commands ###
