"""empty message

Revision ID: 918c95eb8628
Revises: 5b3fe3e85205
Create Date: 2022-03-18 13:19:06.838572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918c95eb8628'
down_revision = '5b3fe3e85205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.create_foreign_key(None, 'child', 'parent', ['parent_id'], ['id'])
    op.drop_column('child', 'user_id')
    op.drop_constraint(None, 'parent', type_='foreignkey')
    op.drop_column('parent', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'parent', 'user', ['user_id'], ['id'])
    op.add_column('child', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.create_foreign_key(None, 'child', 'user', ['user_id'], ['id'])
    op.drop_column('child', 'parent_id')
    # ### end Alembic commands ###
